baseURL = "https://budget.keithjgrant.com/"
languageCode = "en-us"
title = "The Ultimate Budget Spreadsheet"
theme = "book"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
